config/routes.rb
Rails.application.routes.draw do
  resources :pastry_types
  resources :pastries

  get 'menu/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'store#index', :via => :get
  match 'store/:id'=> 'store#show', :as => :store_product, :via => :get
  # get 'store/index'
  # get 'store/show'
  resources :coffees
  get 'coffee_types/index'
  get 'coffee_types/show'
  resources :coffee_types
  resources :beans

  # post 'cart/add/:id', to: 'cart#add', as: 'add_to_cart'
  # delete 'cart/remove/:id', to:'cart#remove', as: 'delete_from_cart'
  post 'coffees/add_to_cart/:id/:quantity', to: 'coffees#add_to_cart', as: 'add_to_cart'
  delete 'coffees/remove_from_cart/:id', to:'coffees#remove_from_cart', as: 'remove_from_cart'
end

app/models/coffee.rb
class Coffee < ApplicationRecord
  # attr_accessible :name, :description, :price, :bean_id

  belongs_to :bean
  belongs_to :coffee_type
  has_many :coffee_flavor_profiles
  has_many :flavor_profiles, through: :coffee_flavor_profiles
  accepts_nested_attributes_for :coffee_flavor_profiles, allow_destroy: true

  validates :name, :description, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: true
  validates :description, length: { maximum: 1500 }

  mount_uploader :image, ImageUploader
  serialize :image, JSON

  def self.search(term)
    if term
      coffees = Coffee.where("name LIKE '%#{term}%'")
        if coffees
          @coffees = coffees
        else
          @coffees = Coffee.all
        end
    else
      @coffees = Coffee.all
    end
  end
end

app/models/coffee_type.rb
class CoffeeType < ApplicationRecord
  has_many :coffees

  validates :name, :description, presence: true
  validates :name, uniqueness: true
  validates :description, length: { maximum: 1000 }
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :set_coffee, only: %i[ show edit update destroy ]
  before_action :initialize_session
  before_action :load_cart

  # GET /coffees or /coffees.json
  def index
    if params['type'].blank? or params['type']['id'].blank?
      @coffees = Coffee.all
    elsif
      coffee_type = CoffeeType.find(params['type']['id'])
      @coffees = coffee_type.coffees
    end
    @coffees = @coffees.search(params[:search]).order(:id).page(params[:page])
  end

  # GET /coffees/1 or /coffees/1.json
  def show
    @action = "show"
  end

  def add_to_cart
    id = params[:id].to_i
    quantity = params[:quantity].to_i
    is_updated = false
      @cart.each_with_index do |item, index|
        if item['id'].to_i == id
          session[:cart][index].update({id: id, quantity: quantity})
          is_updated = true
        end
      end

    if is_updated == false
      session[:cart] << {id: id, quantity: quantity}
      flash[:'notification is-success is-light'] = "Item added successfully"
    end
    redirect_to coffees_path
  end

  def remove_from_cart
    id = params[:id].to_i
    @cart.each_with_index do |item, index|
      if item['id'] == id
        @cart.delete(@cart[index])
        flash[:'notification is-warning is-light'] = "Item is removed from cart"
      end
    end
    redirect_to coffees_path
  end


  def load_cart
    @cart = session[:cart]
    @coffees_in_cart = []
    @cart.each do |item|
      @id =  item['id']
      @coffees_in_cart << Coffee.find(@id)
    end
  end

  def initialize_session
    session[:cart] ||= []
  end
  # GET /coffees/new
  def new
    @coffee = Coffee.new
    @coffee.image = coffee_params[:file]
    @beans = Bean.order(:name)
    @coffee_types = CoffeeType.order(:name)
  end

  # GET /coffees/1/edit
  def edit
    @beans = Bean.order(:name)
    @coffee_types = CoffeeType.order(:name)
  end

  # POST /coffees or /coffees.json
  def create
    @coffee = Coffee.new(coffee_params)
    @coffee.image = coffee_params[:file]

    respond_to do |format|
      if @coffee.save
        # format.html { redirect_to coffee_url(@coffee), notice: "Coffee was successfully created." }
        redirect_to coffee_url(@coffee)
        flash[:info] = "Coffee was successfully created."
        format.json { render :show, status: :created, location: @coffee }
      else
        flash[:notice] = "Coffee was not created."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coffees/1 or /coffees/1.json
  def update
    respond_to do |format|
      puts coffee_params
      @coffee.update(coffee_params)
      if @coffee.update(coffee_params)
        format.html { redirect_to coffee_url(@coffee), notice: "Coffee was successfully updated." }
        format.json { render :show, status: :ok, location: @coffee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coffee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coffees/1 or /coffees/1.json
  def destroy
    @coffee.destroy

    respond_to do |format|
      format.html { redirect_to coffees_url, notice: "Coffee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee
      @coffee = Coffee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coffee_params
      params.require(:coffee).permit(:name, :description, :price, :bean_id, :coffee_type_id, :image, :search, :id, :quantity)
    end
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/views/coffees/_coffee.html.erb
<% if @action == "show" %>
  <div class="column is-three-fifths center">
<% else %>
  <div class="column is-one-third">
<% end %>
  <div class="card" id="<%= dom_id coffee %>">
      <% if @action == "show" %>
        <div class="card-image has-text-centered">
          <%= image_tag coffee.image.to_s if coffee.image.present? %>
        </div>
      <% end %>
    <div class="card-content">
      <% if @action == "show" %>
        <h2 class="title is-4"><%= coffee.name %></h2>
      <% else %>
        <p class="title is-5">
          <strong><%= link_to coffee.name, coffee %></strong>
        </p>
      <% end %>

      <% if @action != "show" %>
        <div class="card-image has-text-centered">
          <%= image_tag coffee.image.thumb.to_s if coffee.image.present? %>
        </div>
      <% end %>

      <p>
        <strong>Bean and Type:</strong>
        <%= coffee.bean.name %> | <%= coffee.coffee_type.name %>
      </p>

        <% if coffee.flavor_profiles.present? %>
          <p>
            <strong>Flavor Profiles:</strong>
              <% flavors = []
              coffee.flavor_profiles.each_with_index do |flavor, index|
                flavors[index] = flavor.name
              end %>
            <%= flavors.join(", ") %>
          </p>
        <% end %>

      <% if @action == "show" %>
        <p>
          <strong>Description:</strong>
          <%= coffee.description %>
        </p>
      <% end %>

      <p>
        <strong>Price:</strong>
        <%= coffee.price == coffee.price ? (number_to_currency coffee.price) : 'Not Applicable' %>
      </p>

      <% if @coffees_in_cart.include?(coffee) %>
        <p><%= button_to 'Remove', remove_from_cart_path(coffee), method: :delete, class: "button mt-4 is-small is-responsive is-dark is-rounded" %></p>
      <% else %>
        <p><%= button_to 'Add to Cart', add_to_cart_path(coffee.id, 1), method: :post, class: "button mt-4 is-small is-responsive is-warning is-rounded" %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/coffees/_form.html.erb
<%= form_with(model: coffee) do |form| %>
  <% if coffee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coffee.errors.count, "error") %> prohibited this coffee from being saved:</h2>

      <ul>
        <% coffee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :bean_id, style: "display: block" %>
    <%= form.collection_select :bean_id, @beans, :id, :name %>
  </div>

  <div>
    <%= form.label :coffee_type_id, style: "display: block" %>
    <%= form.collection_select :coffee_type_id, @coffee_types, :id, :name %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/coffees/edit.html.erb
<h1>Editing coffee</h1>

<%= render "form", coffee: @coffee %>

<br>

<div>
  <%= link_to "Show this coffee", @coffee %> |
  <%= link_to "Back to coffees", coffees_path %>
</div>

app/views/coffees/index.html.erb
<p style="color: green"><%= notice %></p>
<details>
  <summary>Shopping Cart</summary>
  <% if @cart.empty? %>
    <p class="ml-5">Your cart is empty</p>
  <% else %>
    <ul>
      <% @cart.each do |i|
          id = i['id']
          quantity = params['quanitity'] ? params['quanitity'].to_i : i['quantity']
          item = Coffee.find(id)
      %>
          <li class="ml-5 container is-flex is-flex-direction-row">
            <%= item.name %>
            <%= number_to_currency item.price %>
            <%= form_tag add_to_cart_path(id, :quantity), :method => "post" do %>
              <%= text_field_tag :quantity, quantity %>
              <%= button_to '✔', add_to_cart_path(id, quantity), method: :post, class: "is-small is-warning is-rounded" %>
              <%= button_to 'x', remove_from_cart_path(id), method: :delete, class: "ml-2 mt-1 is-small delete" %>
            <% end %>
          </li>
      <% end %>
    </ul>
  <% end %>
</details>
<h1 class="title is-4">Beverages Menu</h1>
<%= form_tag coffees_path, :method => "get" do %>
    <%= text_field_tag :search, params[:search] %>
     <%= collection_select :type, :id, CoffeeType.all.order('name ASC'), :id, :name,{include_blank: 'Select Coffee Type'} %>
    <%= submit_tag("Search", :name => nil)%>
<% end %>
<div id="coffees">
  <div class="columns is-multiline is-variable is-1-mobile is-3-desktop is-6-widescreen">
    <% @coffees.each do |coffee| %>
      <%= render coffee %>
    <% end %>
  </div>
</div>
<%= paginate @coffees %>

app/views/coffees/new.html.erb
<h1>New coffee</h1>

<%= render "form", coffee: @coffee %>

<br>

<div>
  <%= link_to "Back to coffees", coffees_path %>
</div>

app/views/coffees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coffee %>

<div>
  <%= link_to "Edit this coffee", edit_coffee_path(@coffee) %> |
  <%= link_to "Back to coffees", coffees_path %>

  <%= button_to "Destroy this coffee", @coffee, method: :delete %>
</div>