config/routes.rb
Rails.application.routes.draw do
  resources :pastry_types
  resources :pastries

  get 'menu/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'store#index', :via => :get
  match 'store/:id'=> 'store#show', :as => :store_product, :via => :get
  # get 'store/index'
  # get 'store/show'
  resources :coffees
  get 'coffee_types/index'
  get 'coffee_types/show'
  resources :coffee_types
  resources :beans

  # post 'cart/add/:id', to: 'cart#add', as: 'add_to_cart'
  # delete 'cart/remove/:id', to:'cart#remove', as: 'delete_from_cart'
  post 'coffees/add_to_cart/:id/:quantity', to: 'coffees#add_to_cart', as: 'add_to_cart'
  delete 'coffees/remove_from_cart/:id', to:'coffees#remove_from_cart', as: 'remove_from_cart'
end

app/models/pastry.rb
class Pastry < ApplicationRecord
  belongs_to :pastry_type

  validates :name, :description, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: true
  validates :description, length: { maximum: 1500 }

  mount_uploader :image, ImageUploader
  serialize :image, JSON
end

app/models/pastry_type.rb
class PastryType < ApplicationRecord
end

app/controllers/pastries_controller.rb
class PastriesController < InheritedResources::Base
  before_action :set_pastry, only: %i[ show edit update destroy ]
  def show
    @action = "show"
  end

  private
    def set_pastry
      @pastry = Pastry.find(params[:id])
    end

    def pastry_params
      params.require(:pastry).permit(:name, :description, :price, :pastry_type_id)
    end

end

app/helpers/pastries_helper.rb
module PastriesHelper
end

app/views/pastries/_form.html.erb
<%= form_with(model: pastry) do |form| %>
  <% if pastry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pastry.errors.count, "error") %> prohibited this pastry from being saved:</h2>

      <ul>
        <% pastry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :pastry_type_id, style: "display: block" %>
    <%= form.number_field :pastry_type_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pastries/_pastry.html.erb
<div id="<%= dom_id pastry %>">
  <% if @action == "show" %>
    <h2 class="title is-4"><%= pastry.name %></h2>
  <% else %>
    <p>
      <strong><%= link_to pastry.name, pastry %></strong>
    </p>
  <% end %>

  <% if @action == "show" %>
    <%= image_tag pastry.image.to_s if pastry.image.present? %>
  <% else %>
    <%= image_tag pastry.image.thumb.to_s if pastry.image.present? %>
  <% end %>

  <p>
    <%= pastry.pastry_type.name %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;<%= "#{number_to_currency pastry.price}" %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= pastry.description %>
  </p>

  <p><%= link_to 'Add to Cart', '#', class: "button mt-4 is-small is-responsive is-warning is-active is-rounded" %></p>

</div>

app/views/pastries/edit.html.erb
<h1>Editing pastry</h1>

<%= render "form", pastry: @pastry %>

<br>

<div>
  <%= link_to "Show this pastry", @pastry %> |
  <%= link_to "Back to pastries", pastries_path %>
</div>

app/views/pastries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="title is-4">Pastries Menu</h1>

<div id="pastries">
  <% @pastries.each do |pastry| %>
    <%= render pastry %>
  <% end %>
</div>

<%= link_to "New pastry", new_pastry_path %>

app/views/pastries/new.html.erb
<h1>New pastry</h1>

<%= render "form", pastry: @pastry %>

<br>

<div>
  <%= link_to "Back to pastries", pastries_path %>
</div>

app/views/pastries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pastry %>

<div>
  <%= link_to "Edit this pastry", edit_pastry_path(@pastry) %> |
  <%= link_to "Back to pastries", pastries_path %>

  <%= button_to "Destroy this pastry", @pastry, method: :delete %>
</div>