config/routes.rb
Rails.application.routes.draw do
  resources :pastry_types
  resources :pastries

  get 'menu/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'store#index', :via => :get
  match 'store/:id'=> 'store#show', :as => :store_product, :via => :get
  # get 'store/index'
  # get 'store/show'
  resources :coffees
  get 'coffee_types/index'
  get 'coffee_types/show'
  resources :coffee_types
  resources :beans

  # post 'cart/add/:id', to: 'cart#add', as: 'add_to_cart'
  # delete 'cart/remove/:id', to:'cart#remove', as: 'delete_from_cart'
  post 'coffees/add_to_cart/:id/:quantity', to: 'coffees#add_to_cart', as: 'add_to_cart'
  delete 'coffees/remove_from_cart/:id', to:'coffees#remove_from_cart', as: 'remove_from_cart'
end

app/controllers/pastry_types_controller.rb
class PastryTypesController < InheritedResources::Base

  private

    def pastry_type_params
      params.require(:pastry_type).permit(:name, :description)
    end

end

app/helpers/pastry_types_helper.rb
module PastryTypesHelper
end

app/views/pastry_types/_form.html.erb
<%= form_with(model: pastry_type) do |form| %>
  <% if pastry_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pastry_type.errors.count, "error") %> prohibited this pastry_type from being saved:</h2>

      <ul>
        <% pastry_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pastry_types/_pastry_type.html.erb
<div id="<%= dom_id pastry_type %>">
  <p>
    <strong>Name:</strong>
    <%= pastry_type.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= pastry_type.description %>
  </p>

</div>

app/views/pastry_types/edit.html.erb
<h1>Editing pastry type</h1>

<%= render "form", pastry_type: @pastry_type %>

<br>

<div>
  <%= link_to "Show this pastry type", @pastry_type %> |
  <%= link_to "Back to pastry types", pastry_types_path %>
</div>

app/views/pastry_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pastry types</h1>

<div id="pastry_types">
  <% @pastry_types.each do |pastry_type| %>
    <%= render pastry_type %>
    <p>
      <%= link_to "Show this pastry type", pastry_type %>
    </p>
  <% end %>
</div>

<%= link_to "New pastry type", new_pastry_type_path %>

app/views/pastry_types/new.html.erb
<h1>New pastry type</h1>

<%= render "form", pastry_type: @pastry_type %>

<br>

<div>
  <%= link_to "Back to pastry types", pastry_types_path %>
</div>

app/views/pastry_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pastry_type %>

<div>
  <%= link_to "Edit this pastry type", edit_pastry_type_path(@pastry_type) %> |
  <%= link_to "Back to pastry types", pastry_types_path %>

  <%= button_to "Destroy this pastry type", @pastry_type, method: :delete %>
</div>