config/routes.rb
Rails.application.routes.draw do
  resources :pastry_types
  resources :pastries

  get 'menu/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => 'store#index', :via => :get
  match 'store/:id'=> 'store#show', :as => :store_product, :via => :get
  # get 'store/index'
  # get 'store/show'
  resources :coffees
  get 'coffee_types/index'
  get 'coffee_types/show'
  resources :coffee_types
  resources :beans

  # post 'cart/add/:id', to: 'cart#add', as: 'add_to_cart'
  # delete 'cart/remove/:id', to:'cart#remove', as: 'delete_from_cart'
  post 'coffees/add_to_cart/:id/:quantity', to: 'coffees#add_to_cart', as: 'add_to_cart'
  delete 'coffees/remove_from_cart/:id', to:'coffees#remove_from_cart', as: 'remove_from_cart'
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @coffees = Coffee.order(:name)
    @pastries = Pastry.all
  end

  def show
    @product = Coffee.find(params[:id])
  end
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/store/index.html.erb
<h3 class="subtitle is-4">Explore our drinks and pastries listings:</h3>
<p><%= link_to 'Shop Beverages', coffees_path, class: "button is-warning is-focused" %></p>
<p><%= link_to 'Shop Pastries', pastries_path, class: "button is-warning is-focused" %></p>
<p><%= link_to 'Shop All', menu_index_path, class: "button is-warning is-focused" %></p>

app/views/store/show.html.erb
<h1></h1>
<p>Find me in app/views/store/show.html.erb</p>